name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"
  PYTHON_VERSIONS: ""

jobs:

  tests:

    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6,3.7,3.8,3.9]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os != 'ubuntu-latest' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: checks-cache

    - name: Set up git
      run: |
        git config --global user.email "pawamoy@pm.me"
        git config --global user.name "Timothée Mazzucotelli"

    - name: Set up the project
      run: pip install safety copier

    - name: Run the test suite
      run: make test
