name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"
  PYTHON_VERSIONS: ""

jobs:

  tests:
    strategy:
      max-parallel: 4
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        copier-version:
        - "7.2.0"
        - "8.0.0"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' || matrix.python-version == '3.12'}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2.5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up git
      run: |
        git config --global user.email "pawamoy@pm.me"
        git config --global user.name "Timothée Mazzucotelli"

    - name: Set up the project
      run: pip install copier==${{ matrix.copier-version }}

    - name: Run the test suite
      run: make test
